project3/mysimpleapp/config/routes.rb
Rails.application.routes.draw do

  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/new'
  # get 'posts/edit'
  # get 'posts/delete'
  # get 'messege_contents/index'
  # get 'messege_contents/show'
  # get 'messege_contents/new'
  # get 'messege_contents/edit'
  # get 'messege_contents/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users/logout'
  resources :posts do
    member do
      get :delete
    end
    resources :messege_contents do
      member do
        get :delete
      end
    end
  end
 
  resources :messege_contents do
    member do
      get :delete
    end
  end
  resources :users do
    member do
      get :delete
    end
  end
end

project3/mysimpleapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project3/mysimpleapp/app/models/messege_content.rb
class MessegeContent < ApplicationRecord
    belongs_to :post
    belongs_to :user

    scope :sorted, lambda { order("id ASC") }
    scope :newest_first, -> { order("created_at DESC") }
    scope :search, lambda { |qurey| where(["name LIKE ?","%#{qurey}%"]) }
end

project3/mysimpleapp/app/models/post.rb
class Post < ApplicationRecord
    has_many :messege_contents
    belongs_to :user
    has_one_attached :attachment

    scope :sorted, lambda { order("id ASC") }
    scope :newest_first, -> { order("created_at DESC") }
    scope :search, lambda { |qurey| where(["name LIKE ?","%#{qurey}%"]) }
    
end

project3/mysimpleapp/app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    has_many :posts
    has_many :messege_contents

    has_one_attached :attachment

    EMAIL_REGEX= /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i



    

    scope :sorted, lambda { order("id ASC") }
    scope :newest_first, -> { order("created_at DESC") }
    scope :search, lambda { |qurey| where(["name LIKE ?","%#{qurey}%"]) }


    validates :email, :length => {:maximum => 50},
                  :presence => true,
                  :format => {:with => EMAIL_REGEX},
                  :confirmation => true
                  
    validates :username, :length =>{:within => 8..25},
                        :uniqueness => true,
                        :presence => true

    validates :first_name, :presence => true ,
                       :length => {:maximum => 25}
    validates :last_name, :presence => true ,
                      :length => {:maximum => 25}


end

project3/mysimpleapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    def confirm_logged_in
      unless session[:user_id]
        flash[:notice]="Please log in first."
        redirect_to(users_path)
      end
    end
  
  
  
end

project3/mysimpleapp/app/controllers/messege_contents_controller.rb
class MessegeContentsController < ApplicationController
  layout 'application'
  before_action :confirm_logged_in
  def index
    @user=User.sorted
    @post=Post.find(session[:post_id])
    @messages=@post.messege_contents
    render('show')
  end

  def show
    @user=User.sorted
    @user1=User.find(session[:id])
    @post=Post.find(session[:post_id])
    @messages=@post.messege_contents
  end

  def new
    @messages = MessegeContent.new
    @post=Post.find(session[:post_id])
    @user1=User.find(session[:user_id])

  end

  def create
    @post=Post.find(session[:post_id])
    @user1=User.find(session[:user_id])
   # @article = Post.find(params[:article_id])
    @messages = @post.messege_contents.create(comment_params)

    if @messages.save
      #if save succeeds, redirect to index actions
      flash[:notice] = "Replied successfully"
      redirect_to(post_path(@post))
    else
      #if save fails, redirect to the form page to fix
    end
  end

  def edit
    @post=Post.find(params[:id])
    @messages=@post.messege_contents.find(params[:post_id])
  end

  def update  
    @post=Post.find(session[:post_id])
    @messages=@post.messege_contents.find(params[:id])
    if @messages.update_attributes(message_params)
      #if save succeeds, redirect to index actions
      flash[:notice] = "Replied successfully"
      redirect_to(post_path(@post))
    else
      #if save fails, redirect to the form page to fix
      render('edit')
    end
  end

  def delete
    @post=Post.find(params[:id])
    @messages=@post.messege_contents.find(params[:post_id])
  end

  def destroy
    @post=Post.find(session[:post_id])
    @messages=@post.messege_contents.find(params[:id])
    @messages.destroy

    flash[:notice] = "post deleated successfully"
    redirect_to(post_path(@post))
  end

  private

  def message_params
    params.require(:messege_content).permit(:content, :post_id, :user_id)
  end

  def comment_params
    params.require(:messege_content).permit(:user_id,:post_id, :content, :body)
  end  

end

project3/mysimpleapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  layout 'for_post'
  before_action :confirm_logged_in
  before_action :set_user, only: [:show , :new, :create, :index]

  def index
    @post= Post.sorted
  end


  def show
    @post= Post.find(params[:id])
    @messages = @post.messege_contents
    puts @messages
   
  end


  def new
    @post=Post.new
  end


  def create
    @post=Post.new(post_params)
    if @post.save
      #if save succeeds, redirect to index actions
      flash[:notice] = "post created successfully"
      redirect_to(posts_path)
    else
      render('new')
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      #if save succeeds, redirect to index actions
      flash[:notice] = "Post updated successfully"
      redirect_to(posts_path)
    else
      render('edit')
    end
  end

  def delete
    @post = Post.find(params[:id])
  end
  def destroy

    @post = Post.find(params[:id])
    @post.destroy

    flash[:notice] = "Page deleated successfully"
    redirect_to(posts_path)
  end

  private

    def set_user
      @user1 =User.find(session[:user_id])

    end

    def post_params
    
        params.require(:post).permit(:user_id, :post_title, :post_content,:attachment)

    end

end

project3/mysimpleapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'

  def index
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      
      end
    if authorized_user
    
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are logged in. as #{params[:username]}"
      redirect_to(posts_path)

    else
      flash[:notice]="Wrong Username/password combination"
      render('index')
    end
    end
  end
  

  def show
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(users_params)
    if @user.save
      UserMailer.with(user: @user).signup_confirmation.deliver_now
      #if save succeeds, redirect to index actions
      flash[:notice] = "Sign up successfully login now"
      redirect_to(users_path)
    else
      #if save fails, redirect to the form page to fix
      render('new')
    end
  end

  def edit

  end

  def delete
  end

  def logout
    session[:username]= nil
    flash[:notice]='Logged out'
    redirect_to(users_path)
  end

  private

  def users_params
    params.require(:user).permit(:first_name, :last_name, :password, :username, :email,:attachment)
  end
end

project3/mysimpleapp/app/helpers/application_helper.rb
module ApplicationHelper
end

project3/mysimpleapp/app/helpers/form_helper.rb
module FormHelper
    def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

project3/mysimpleapp/app/helpers/messege_contents_helper.rb
module MessegeContentsHelper
end

project3/mysimpleapp/app/helpers/posts_helper.rb
module PostsHelper
end

project3/mysimpleapp/app/helpers/users_helper.rb
module UsersHelper
end

project3/mysimpleapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysimpleapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom shadow-sm rounded">
    <a class="navbar-brand" href="#">SQUARE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
      aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active ml-5">
          <a class="nav-link  border-primary" href="#">About<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2 rounded-pill d-none d-sm-block" type="text" placeholder="Search">
      </form>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#"> <img src="download.jpeg" class="rounded-circle mr-5"
              style="width:30px; height:30px;" alt=""> </a>
        </li>
        </li>
        <li class="nav-item">
          <button class="btn btn-primary rounded-pill btn-sm"><%= link_to("Create new user", new_user_path, :class => 'back-link')%></button>
        </li>
      </ul>
    </div>
  </nav>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <p id="copyright"> &copy;something.com</p>
    </div>

  </body>
</html>

project3/mysimpleapp/app/views/layouts/for_post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom shadow-sm rounded">
    <a class="navbar-brand" href="#">SQUARE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
      aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active ml-5">
          <a class="nav-link border-bottom border-primary" href="#">About<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2 rounded-pill d-none d-sm-block" type="text" placeholder="Search">
      </form>

      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
     
      <span class= "identity"><%=@user1.first_name%>  <%if @user1.attachment.attached?%><%=image_tag(@user1.attachment, size: "30", class: "menu_icon1")%><%else%> <img src="https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg" alt="" style=" width:30px; height:30px;" class= "identity menu_icon1"><%  end %></span>
       </li>
      <li class="nav-item">
      <button class="btn btn-warning rounded-pill btn-sm mr-3"><%= link_to("Add new Posts", new_post_path , :class => 'action new') %></button>
    </li>
        
        <li class="nav-item">
          <button class="btn btn-warning rounded-pill btn-sm "><%= link_to("logout", users_logout_path, :class => 'action delete')%></button>
        </li>
      </ul>
    </div>
  </nav>
    </header>


 <div class="container-fluid bg-light">
    <div class="row ">
        <div class="col-sm-2 p-0 mynav2 ">
            <nav class="navbar navbar-sm navbar-light bg-light p-0 mynav3 ">
            <a class="navbar-brand  d-block d-sm-none" href="#"></a>
            <button class="navbar-toggler d-block d-sm-none" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-start p-2 m-0 mynav2" id="navbarNav">
                <ul class="navbar-nav mynav2">
                <li class="nav-item border-top mylistitem">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-home"></i></span> Home
                    <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item border-top active">
                    <a class="nav-link " href="#"><span class="input-group-addon"><i class="fa fa-home"></i></span>
                    Post</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-file-o"></i></span>
                    Page</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-plug"></i></span>
                    Plugin</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-home"></i></span> Post</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span> <span class="input-group-addon"><i
                            class="fa fa-user-plus"></i></span> Support center</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-home"></i></span> Media</a>
                </li>
                <li class="nav-item border-top">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-home"></i></span>
                    Apperence</a>
                </li>
                <li class="nav-item border-top border-bottom">
                    <a class="nav-link" href="#"><span class="input-group-addon"><i class="fa fa-inr"></i></span>
                    Ecommerce</a>
                </li>

                </ul>
            </div>
            </nav>
        </div>
    <!--main contain-->
        <div class="col-sm-10 mt-5">
        <%= yield %>
        </div>
     </div>
</div>
          
      <div class="row" id="footer">
        <p id="copyright"> &copy;something.com</p>
      </div>
  
    </body>
  </html>
  

project3/mysimpleapp/app/views/layouts/primary.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Simple rails application</title>

    <%= stylesheet_link_tag('application', :media => 'all') %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    
        <div id="content">
          <%= yield %>
        </div>
        <div id="footer">
          <p id="copyright"> &copy;something.com</p>
        </div>
      

  </body>
</html>

project3/mysimpleapp/app/views/messege_contents/delete.html.erb
<%= link_to("<< Back to List", messege_contents_path, :class => 'back-link')%>
<div class="sections delete">
  <h2>Delete Post</h2>
  <%= form_for(@messages, :method => 'delete') do |f| %>
  <!--:method => 'delete' must be added to inform rails that it is delete action not update-->

  <p>Are you sure you want to parmanently delete this post?</p>

  <div class="form-bottons">
    <%=f.submit("Delete post")%>
  </div>
  <% end %>
</div>

project3/mysimpleapp/app/views/messege_contents/edit.html.erb
<%= link_to("<< Back to List", post_messege_contents_path, :class => 'back-link')%>

<div class="subjects new">
  <h2>Edit replay</h2>
  <%= form_for(@messages) do |f| %>
    
  <!-- alternative and discribtive way to write the above code is "form_for(@subject, :url => subjects_path, :method=> 'post' ) do |f| %>-->
    <table summary="Subject form fields">
  
    <tr>
      <th>post</th>
      <td><%= f.text_area(:content, :size => 40*10) %></td>
    </tr>
  </table>

  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.hidden_field :user_id, :value => @post.user_id %>
  <div class="form-bottons">
    <%=f.submit("Reply")%>
  </div>
  <%end%>
</div>

project3/mysimpleapp/app/views/messege_contents/index.html.erb
<div class="subjects index">
<h2>Post</h2>

<%= link_to("Add new Post", new_messege_content_path , :class => 'action new') %>

<br/>

<table class="listing" summary="Subject list" border="1px" style="border-collapse: collapse;">
  <tr class="header">
    <td>#</td>
    <th><%= @post.user.first_name + ' ' + @post.user.last_name %> says </td></th>
    <th> <%= @post.post_content %></th>
    <td></td>
  </tr>
<% @messages.each do |message| %>
  <tr>
    <td><%= message.id %></td>
    <td><%= @user.first_name + ' ' + @user.last_name %> says </td>
    <td class="center"><%= message.content %></td>
    
    <td class="actions">
      <%= link_to("show message and comment", messege_content_path(message), :class => 'action show')%> |
     | <%= link_to("Edit post", edit_messege_content_path(message), :class => 'action edit')%> |
      | <%= link_to("Delete post", delete_messege_content_path(message), :class => 'action delete')%>
    </td>
  </tr>
  <% end %>
</table>

</div>

project3/mysimpleapp/app/views/messege_contents/new.html.erb
<%= link_to("<< Back to Comment", post_messege_contents_path, :class => 'back-link')%>

<div class="subjects new">
  <h2>Create replay</h2>
  <%= form_for(@messages) do |f| %>
  <!-- alternative and discribtive way to write the above code is "form_for(@subject, :url => subjects_path, :method=> 'post' ) do |f| %>-->
    <table summary="Subject form fields">
    
    <tr>
      <th>User : </th>
      <td><%= @user1.username %></td>
    </tr>
    <tr>
      <th>post</th>
      <td><%= f.text_area(:content, :size => 40*10) %></td>
    </tr>
  </table>

  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.hidden_field :user_id, :value =>  @user1.id%>
  <div class="form-bottons">
    <%=f.submit("Reply")%>
  </div>
  <%end%>
</div>

project3/mysimpleapp/app/views/messege_contents/show.html.erb
<div class="subjects index">
<h2>Comments</h2>

<br/>
<br/>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %>
</div>
<% end %>

<%= link_to("back to posts page", posts_path , :class => 'action new') %>
<br/>

<table class="listing" summary="Subject list" >
<tr style=" background: blue; ">
    
<th>Users</th>
<th > Description</th>

</tr>
  <tr class="header">
    
    <th> <%= @post.user.first_name + ' ' + @post.user.last_name %>  says: </th>
    <th style =" border: 1px solid black; width: 400px; background: grey;"> <%= @post.post_content %>
    <br/> <span style="font-size: 8px;"><%= @post.created_at%></span> </th>
    <th></th>
  </tr>
  <tr class="header">
    
    <th></th>
    <th> </th>
    <td></td>
  </tr>
<% @messages.each do |message| %>
  <tr>
  
    
    <td><%= message.user.first_name %></td>
    <td class="center" style =" border: 1px solid black; text-align: center;"> <%= message.content %></td>
    
    <td class="actions">
    <% if message.user_id == session[:user_id] %>
      <%= link_to("Edit post", edit_messege_content_path(message), :class => 'action edit')%> |
      | <%= link_to("Delete post", delete_messege_content_path(message), :class => 'action delete')%>
      <%end%>
    </td>
  </tr>
  <% end %>
</table>
 <%= link_to("Add new reply", new_messege_content_path , :class => 'action new') %>

</div>

project3/mysimpleapp/app/views/posts/_form.html.erb
<table summary="Subject form fields">
<tr>
  <th>User_id</th>
  <td><%= f.text_field(:user_id) %></td>
</tr>

<tr>
<th>Post title</th>
<td><%= f.text_field(:post_title) %></td>
</tr>

<tr>
<th>Discribtion</th>
<td><%= f.text_area(:post_content, :size => 50*20) %></td>
</tr>

<tr>
  <th>Upload</th>
  <td><%= f.file_field(:attachment) %></td>
</tr>
</table>
<div class="form-bottons">
<%=f.submit("Edit Post")%>
</div>

project3/mysimpleapp/app/views/posts/delete.html.erb
<%= link_to("<< Back to List", posts_path, :class => 'back-link')%>
<div class="sections delete">
  <h2>Delete Post</h2>
  <%= form_for(@post, :method => 'delete') do |f| %>
  <!--:method => 'delete' must be added to inform rails that it is delete action not update-->

  <p>Are you sure you want to parmanently delete this post?</p>

  <div class="form-bottons">
    <%=f.submit("Delete post")%>
  </div>
  <% end %>
</div>

project3/mysimpleapp/app/views/posts/edit.html.erb
<%= link_to("<< Back to Post", posts_path, :class => 'back-link')%>

<div class="subjects new">
  
  <!-- alternative and discribtive way to write the above code is "form_for(@subject, :url => subjects_path, :method=> 'post' ) do |f| %>-->
    <h2>Edit post</h2>
    <%= form_for(@post) do |f| %>
    <!-- alternative and discribtive way to write the above code is "form_for(@subject, :url => subjects_path, :method=> 'post' ) do |f| %>-->
      <%= render(:partial => 'form', :locals => {:f => f})%>
    <%end%>
  </div>

project3/mysimpleapp/app/views/posts/index.html.erb
<div class="subjects index">

<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %>
</div>
<% end %>
<br/>




<% @post.each do |post| %>
  <tr>
    <div class="contenters">
    <div class="content_view"><span class="user_name"><%= post.user.first_name + ' ' + post.user.last_name %></span>
    <div class="content_view"><%= post.post_title %></div></div>
    
    <div class="actions">
      <%= link_to("Details", post_path(post), :class => 'action show')%> |
      <% if post.user_id == session[:user_id] %>
     | <%= link_to("Edit post", edit_post_path(post), :class => 'action edit')%> |
      | <%= link_to("Delete post", delete_post_path(post), :class => 'action delete')%>
      <%end%>
    </div>
 <hr/>
  <% end %>




</div>

project3/mysimpleapp/app/views/posts/new.html.erb
<h2>Create post</h2>
<div class="subjects new pl-3">
 
  <%= link_to("<< Back to Post", posts_path, :class => 'back-link')%>
  <%= form_for(@post) do |f| %>
  <!-- alternative and discribtive way to write the above code is "form_for(@subject, :url => subjects_path, :method=> 'post' ) do |f| %>-->
    <%= render(:partial => 'form', :locals => {:f => f})%>
  
  <%end%>
</div>

project3/mysimpleapp/app/views/posts/show.html.erb
<div class="subjects index">
<h2>Comments</h2>

<br/>
<br/>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %>
</div>
<% end %>

<%= link_to("back to posts page", posts_path , :class => 'action new') %>
<br/>

<table class="listing" summary="Subject list" >
<tr style=" background: blue; ">
    
<th>Users</th>
<th > Description</th>

</tr>
  <tr class="header">
    
    <th class="listing2"> <%= @post.user.first_name + ' ' + @post.user.last_name %>  says: </th>
    <th style =" border: 1px solid black; width: 400px; background: grey;"> <%= @post.post_content %>
    <% if @post.attachment.attached? %>
    <br/><%= image_tag(@post.attachment, style: "width:150px;")%><% end %><br/> <span style="font-size: 8px;"><%= @post.created_at%></span> </th>
    <th></th>
  </tr>
  <tr ><td colspan=2> </td></tr>

<% @messages.each do |message| %>
  <tr class="listing1"> 
    <td class="listing2"><%= message.user.first_name %></td>
    <td class="center" style =" border: 1px solid black; text-align: center;"> <%= message.content %></td>
    
    <td class="actions_other">
    <% if message.user_id == session[:user_id] %>
      <%= link_to("Edit post", edit_post_messege_content_path(message), :class => 'action edit')%> |
      | <%= link_to("Delete post", delete_post_messege_content_path(message), :class => 'action delete')%>
      <%end%>
    </td>
  </tr>
  <% end %>
</table>




<h2>Add a comment:</h2>
<%= form_with(model: [ @post, @post.messege_contents.build ], local: true) do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

project3/mysimpleapp/app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

project3/mysimpleapp/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

project3/mysimpleapp/app/views/users/index.html.erb
<h2> Log In Page</h2>

<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>


<br/>



<div class="login p-3">
  <%= form_tag(users_path, :method => :get) do%>
  <table>
    <tr>
      <td><%= label_tag(:username)%></td>
      <td><%= text_field_tag(:username, params[:username])%></td>
    </tr>
    <tr>
      <td><%= label_tag(:password)%></td>
      <td><%= password_field_tag(:password)%></td>
    </tr>
    <tr>
      <td>&nbsp</td>
      <td><%= submit_tag("Log In")%></td>
    </tr>
  </table>
  <%end%>
</div>

project3/mysimpleapp/app/views/users/new.html.erb
<% def msg(status) return "#{status}" end %>

<div class="pages new">
  <h2>Create Users</h2>
 
  <%= link_to(" <-- Back to loging page", users_path, :class => 'back-link')%>
  <br/>
  <br/>
  <div class="p-3">
     <%= form_for(@user) do |f| %>
    <table summary="Pages form fields">
        <tr>
            <th>First Name</th>
            <td><%= f.text_field(:first_name)%></td>
            <td class="input_fields"><%= @user.errors[:first_name].join('. ')%></td>
            
        </tr>
        <tr>
            <th>Last Name</th>
            <td><%= f.text_field(:last_name) %></td>
            <td class="input_fields"><%= @user.errors[:last_name].join('. ')%></td>
        </tr>
        <tr>
            <th>Password</th>
            <td><%= f.password_field(:password) %></td>
            <td class="input_fields"><%= @user.errors[:password].join('. ')%></td>
        </tr>
        <tr>
            <th>Username</th>
            <td><%= f.text_field(:username) %></td>
            <td class="input_fields"><%= @user.errors[:username].join('. ')%></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><%= f.text_field(:email) %></td>
            <td class="input_fields"><%= @user.errors[:email].join('. ')%></td>
        </tr>
        <tr>
            <th>Upload Profile Picture</th>
            <td><%= f.file_field(:attachment) %></td>
        </tr>

    </table>
    <br/>
    <div class="form-bottons">
        <%=f.submit("Create User")%>
    </div>
    <%end%>
    </div>
</div>

project3/mysimpleapp/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>